### PR TITLE
Proposal for flytectl

### PR DESCRIPTION
**Pull request by kumare3**

### CODE REVIEW

**Comment by wild-endeavor** [comment]
Haven't read yet, but are we doing proposals in Github now?

**Comment by kumare3** [comment]
> Haven't read yet, but are we doing proposals in Github now?
Not really, It made sense in this case, because this can easily become documentation.

**Comment by brucearctor** [comment]
Right now is coded for `flytectl get projects`.  Do we want the plural, singular, or for either (project and/or projects) to be valid?

**Comment by brucearctor** [comment]
Is there a style guide in place here -- wondering why it looks like lines are cut at 200 characters in the README?  (Looks fine, verifying that is desired/purposeful).

**Comment by kumare3** [comment]
I don’t think there is a style guide we have for markdown. But for go we do, we will add the boilerplate to this repo

**Pull request merged**
